codecov:
  branch: develop

coverage:
  status:
    project:
      default:
        target: auto
        branches:
          - develop
          - main

ignore:
  - "cmd/**"
  - "internal/server/server.go"
